/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author nanang saiful
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Homeinputpegawai
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lihatpegawai = new javax.swing.JButton();
        inputpembeli = new javax.swing.JButton();
        lihatpembeli = new javax.swing.JButton();
        INPUT = new javax.swing.JButton();
        Lihatobat = new javax.swing.JButton();
        inputobat = new javax.swing.JButton();
        lihatdistributor = new javax.swing.JButton();
        inputdistributor = new javax.swing.JButton();
        lihatransaksi = new javax.swing.JButton();
        lihatrestock = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Untitle.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("apotik As-syifa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lihatpegawai.setText("lihat pegawai");
        lihatpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatpegawaiActionPerformed(evt);
            }
        });
        jPanel2.add(lihatpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 174, 51));

        inputpembeli.setText("Input pembeli");
        inputpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpembeliActionPerformed(evt);
            }
        });
        jPanel2.add(inputpembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 174, 48));

        lihatpembeli.setText("lihat pembeli");
        lihatpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatpembeliActionPerformed(evt);
            }
        });
        jPanel2.add(lihatpembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 174, 51));

        INPUT.setText("Input pegawai");
        INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUTActionPerformed(evt);
            }
        });
        jPanel2.add(INPUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 174, 51));

        Lihatobat.setText("lihat obat");
        jPanel2.add(Lihatobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 174, 46));

        inputobat.setText("input obat");
        inputobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputobatActionPerformed(evt);
            }
        });
        jPanel2.add(inputobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 174, 46));

        lihatdistributor.setText("lihat distributor");
        jPanel2.add(lihatdistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 174, 50));

        inputdistributor.setText("input distributor");
        inputdistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputdistributorActionPerformed(evt);
            }
        });
        jPanel2.add(inputdistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 174, 50));

        lihatransaksi.setText("lihat transaksi");
        jPanel2.add(lihatransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 174, 50));

        lihatrestock.setText("lihat restock");
        lihatrestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatrestockActionPerformed(evt);
            }
        });
        jPanel2.add(lihatrestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 174, 46));

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 163, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Untitle.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 70, 450, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("apotik As-syifa");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUTActionPerformed
        // TODO add your handling code here:t
    }//GEN-LAST:event_INPUTActionPerformed

    private void lihatpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatpegawaiActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_lihatpegawaiActionPerformed

    private void inputobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputobatActionPerformed

    private void inputpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputpembeliActionPerformed

    private void lihatpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatpembeliActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void inputdistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputdistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputdistributorActionPerformed

    private void lihatrestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatrestockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatrestockActionPerformed

  public void addactionlistener(ActionListener e){
      INPUT.addActionListener(e);
      lihatpegawai.addActionListener(e);
      inputobat.addActionListener(e);
      Lihatobat.addActionListener(e);
      lihatpembeli.addActionListener(e);
      inputpembeli.addActionListener(e);
      lihatransaksi.addActionListener(e);
      inputdistributor.addActionListener(e);
      lihatdistributor.addActionListener(e);
      logout.addActionListener(e);
      lihatrestock.addActionListener(e);
  }
  public  JButton getinputdistributor(){
      return inputdistributor;
  }
  public JButton getlihatdistributor(){
      return lihatdistributor;
  }
  public JButton getinput(){
      return INPUT;
  }
  public JButton getlihatpegawai(){
      return lihatpegawai;
  }
  public JButton getinputobat(){
      return inputobat;
  }
  public JButton getlihatobat(){
      return Lihatobat;
  }
  public JButton getlihatpembeli(){
      return lihatpembeli;
  }
  public JButton getinputpembeli(){
      return inputpembeli;
  }

  public JButton getlihattransaksi(){
      return lihatransaksi;
  }
  public JButton getLogout(){
      return logout;
  }
  public JButton getliatrestock(){
      return lihatrestock;
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INPUT;
    private javax.swing.JButton Lihatobat;
    private javax.swing.JButton inputdistributor;
    private javax.swing.JButton inputobat;
    private javax.swing.JButton inputpembeli;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lihatdistributor;
    private javax.swing.JButton lihatpegawai;
    private javax.swing.JButton lihatpembeli;
    private javax.swing.JButton lihatransaksi;
    private javax.swing.JButton lihatrestock;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
